% Contains macros for the 8 ordinal and cardinal directions


%******************************************* For Human Agents ************************************************
#BeginMacro(SELF_HUMAN)
(0,0)~comfort_human
#EndMacro

#BeginMacro(E_HUMAN)
(0,1)~comfort_human
#EndMacro

#BeginMacro(W_HUMAN)
(0,-1)~comfort_human
#EndMacro

#BeginMacro(N_HUMAN)
(-1,0)~comfort_human
#EndMacro

#BeginMacro(S_HUMAN)
(1,0)~comfort_human
#EndMacro

#BeginMacro(NE_HUMAN)
(-1,1)~comfort_human
#EndMacro

#BeginMacro(NW_HUMAN)
(-1,-1)~comfort_human
#EndMacro

#BeginMacro(SE_HUMAN)
(1,1)~comfort_human
#EndMacro

#BeginMacro(SW_HUMAN)
(1,-1)~comfort_human
#EndMacro
%***************************************************************************************************************


%******************************************* For Monster Agents ************************************************
#BeginMacro(SELF_MONS)
(0,0)~comfort_mons
#EndMacro

#BeginMacro(E_MONS)
(0,1)~comfort_mons
#EndMacro

#BeginMacro(W_MONS)
(0,-1)~comfort_mons
#EndMacro

#BeginMacro(N_MONS)
(-1,0)~comfort_mons
#EndMacro

#BeginMacro(S_MONS)
(1,0)~comfort_mons
#EndMacro

#BeginMacro(NE_MONS)
(-1,1)~comfort_mons
#EndMacro

#BeginMacro(NW_MONS)
(-1,-1)~comfort_mons
#EndMacro

#BeginMacro(SE_MONS)
(1,1)~comfort_mons
#EndMacro

#BeginMacro(SW_MONS)
(1,-1)~comfort_mons
#EndMacro
%***************************************************************************************************************


%******************************************* For Alien Agents **************************************************
#BeginMacro(SELF_ALIEN)
(0,0)~comfort_alien
#EndMacro

#BeginMacro(E_ALIEN)
(0,1)~comfort_alien
#EndMacro

#BeginMacro(W_ALIEN)
(0,-1)~comfort_alien
#EndMacro

#BeginMacro(N_ALIEN)
(-1,0)~comfort_alien
#EndMacro

#BeginMacro(S_ALIEN)
(1,0)~comfort_alien
#EndMacro

#BeginMacro(NE_ALIEN)
(-1,1)~comfort_alien
#EndMacro

#BeginMacro(NW_ALIEN)
(-1,-1)~comfort_alien
#EndMacro

#BeginMacro(SE_ALIEN)
(1,1)~comfort_alien
#EndMacro

#BeginMacro(SW_ALIEN)
(1,-1)~comfort_alien
#EndMacro
%***************************************************************************************************************