% Contains macros for the 8 ordinal and cardinal directions

#BeginMacro(SELF)
(0,0)~preference
#EndMacro

#BeginMacro(E)
(0,1)~preference
#EndMacro

#BeginMacro(W)
(0,-1)~preference
#EndMacro

#BeginMacro(N)
(-1,0)~preference
#EndMacro

#BeginMacro(S)
(1,0)~preference
#EndMacro

#BeginMacro(NE)
(-1,1)~preference
#EndMacro

#BeginMacro(NW)
(-1,-1)~preference
#EndMacro

#BeginMacro(SE)
(1,1)~preference
#EndMacro

#BeginMacro(SW)
(1,-1)~preference
#EndMacro